export function cacheDom() {
  return {
    shell: document.querySelector(".shell"),
    topbar: document.querySelector(".topbar"),
    themeToggle: document.getElementById("themeToggle"),
    refreshButton: document.getElementById("refreshButton"),
    messageForm: document.getElementById("messageForm"),
    rankingPrev: document.getElementById("rankingPrev"),
    rankingNext: document.getElementById("rankingNext"),
    drawerRankingPrev: document.getElementById("drawerRankingPrev"),
    drawerRankingNext: document.getElementById("drawerRankingNext"),
    openRightDrawer: document.getElementById("openRightDrawer"),
    drawerBackdrop: document.getElementById("drawerBackdrop"),
    profileButton: document.getElementById("profileButton"),
    backToTopics: document.getElementById("backToTopics"),
    contactAdminButton: document.getElementById("contactAdminButton"),
    storeButton: document.getElementById("storeButton"),
    paletteButton: document.getElementById("paletteButton"),
    refreshState: document.getElementById("refreshState"),
    chatTopicName: document.getElementById("chatTopicName"),
    chatTopicDescription: document.getElementById("chatTopicDescription"),
    rankingsTitle: document.getElementById("rankingsTitle"),
    drawerRankingsTitle: document.getElementById("drawerRankingsTitle"),
    messageInput: document.getElementById("messageInput"),
    messageStream: document.getElementById("messageStream"),
    topicList: document.getElementById("topicList"),
    leftDrawerTopics: document.getElementById("leftDrawerTopics"),
    userList: document.getElementById("userList"),
    drawerUserList: document.getElementById("drawerUserList"),
    rankingList: document.getElementById("rankingList"),
    drawerRankingList: document.getElementById("drawerRankingList"),
    leftDrawer: document.getElementById("leftDrawer"),
    rightDrawer: document.getElementById("rightDrawer"),
    drawerCloseButtons: Array.from(document.querySelectorAll("[data-close-drawer]"))
  };
}
